//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 05:07:04 PM CET 
//


package org.knime.ext.tableau.hyper.sendtable.api.binding;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.knime.ext.tableau.hyper.sendtable.api.binding package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.knime.ext.tableau.hyper.sendtable.api.binding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FrequencyDetailsType }
     * 
     */
    public FrequencyDetailsType createFrequencyDetailsType() {
        return new FrequencyDetailsType();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link GranteeCapabilitiesType }
     * 
     */
    public GranteeCapabilitiesType createGranteeCapabilitiesType() {
        return new GranteeCapabilitiesType();
    }

    /**
     * Create an instance of {@link SiteType }
     * 
     */
    public SiteType createSiteType() {
        return new SiteType();
    }

    /**
     * Create an instance of {@link TsRequest }
     * 
     */
    public TsRequest createTsRequest() {
        return new TsRequest();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link TableauCredentialsType }
     * 
     */
    public TableauCredentialsType createTableauCredentialsType() {
        return new TableauCredentialsType();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link FavoriteType }
     * 
     */
    public FavoriteType createFavoriteType() {
        return new FavoriteType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link PermissionsType }
     * 
     */
    public PermissionsType createPermissionsType() {
        return new PermissionsType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link ScheduleType }
     * 
     */
    public ScheduleType createScheduleType() {
        return new ScheduleType();
    }

    /**
     * Create an instance of {@link TagListType }
     * 
     */
    public TagListType createTagListType() {
        return new TagListType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link WorkbookType }
     * 
     */
    public WorkbookType createWorkbookType() {
        return new WorkbookType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     * 
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link TsResponse }
     * 
     */
    public TsResponse createTsResponse() {
        return new TsResponse();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link DataSourceListType }
     * 
     */
    public DataSourceListType createDataSourceListType() {
        return new DataSourceListType();
    }

    /**
     * Create an instance of {@link ExtractListType }
     * 
     */
    public ExtractListType createExtractListType() {
        return new ExtractListType();
    }

    /**
     * Create an instance of {@link GroupListType }
     * 
     */
    public GroupListType createGroupListType() {
        return new GroupListType();
    }

    /**
     * Create an instance of {@link ProjectListType }
     * 
     */
    public ProjectListType createProjectListType() {
        return new ProjectListType();
    }

    /**
     * Create an instance of {@link RevisionListType }
     * 
     */
    public RevisionListType createRevisionListType() {
        return new RevisionListType();
    }

    /**
     * Create an instance of {@link ScheduleListType }
     * 
     */
    public ScheduleListType createScheduleListType() {
        return new ScheduleListType();
    }

    /**
     * Create an instance of {@link SiteListType }
     * 
     */
    public SiteListType createSiteListType() {
        return new SiteListType();
    }

    /**
     * Create an instance of {@link UserListType }
     * 
     */
    public UserListType createUserListType() {
        return new UserListType();
    }

    /**
     * Create an instance of {@link WorkbookListType }
     * 
     */
    public WorkbookListType createWorkbookListType() {
        return new WorkbookListType();
    }

    /**
     * Create an instance of {@link SubscriptionListType }
     * 
     */
    public SubscriptionListType createSubscriptionListType() {
        return new SubscriptionListType();
    }

    /**
     * Create an instance of {@link ConnectionListType }
     * 
     */
    public ConnectionListType createConnectionListType() {
        return new ConnectionListType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link FavoriteListType }
     * 
     */
    public FavoriteListType createFavoriteListType() {
        return new FavoriteListType();
    }

    /**
     * Create an instance of {@link FileUploadType }
     * 
     */
    public FileUploadType createFileUploadType() {
        return new FileUploadType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link ServerInfo }
     * 
     */
    public ServerInfo createServerInfo() {
        return new ServerInfo();
    }

    /**
     * Create an instance of {@link ViewListType }
     * 
     */
    public ViewListType createViewListType() {
        return new ViewListType();
    }

    /**
     * Create an instance of {@link TaskListType }
     * 
     */
    public TaskListType createTaskListType() {
        return new TaskListType();
    }

    /**
     * Create an instance of {@link StatusNoteType }
     * 
     */
    public StatusNoteType createStatusNoteType() {
        return new StatusNoteType();
    }

    /**
     * Create an instance of {@link StatusNoteListType }
     * 
     */
    public StatusNoteListType createStatusNoteListType() {
        return new StatusNoteListType();
    }

    /**
     * Create an instance of {@link ProductVersion }
     * 
     */
    public ProductVersion createProductVersion() {
        return new ProductVersion();
    }

    /**
     * Create an instance of {@link ExtractRefreshJobType }
     * 
     */
    public ExtractRefreshJobType createExtractRefreshJobType() {
        return new ExtractRefreshJobType();
    }

    /**
     * Create an instance of {@link RevisionType }
     * 
     */
    public RevisionType createRevisionType() {
        return new RevisionType();
    }

    /**
     * Create an instance of {@link ImportDirectiveType }
     * 
     */
    public ImportDirectiveType createImportDirectiveType() {
        return new ImportDirectiveType();
    }

    /**
     * Create an instance of {@link SubscriptionContentType }
     * 
     */
    public SubscriptionContentType createSubscriptionContentType() {
        return new SubscriptionContentType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link CapabilityType }
     * 
     */
    public CapabilityType createCapabilityType() {
        return new CapabilityType();
    }

    /**
     * Create an instance of {@link DomainDirectiveType }
     * 
     */
    public DomainDirectiveType createDomainDirectiveType() {
        return new DomainDirectiveType();
    }

    /**
     * Create an instance of {@link ParentType }
     * 
     */
    public ParentType createParentType() {
        return new ParentType();
    }

    /**
     * Create an instance of {@link IntervalType }
     * 
     */
    public IntervalType createIntervalType() {
        return new IntervalType();
    }

    /**
     * Create an instance of {@link ConnectionCredentialsType }
     * 
     */
    public ConnectionCredentialsType createConnectionCredentialsType() {
        return new ConnectionCredentialsType();
    }

    /**
     * Create an instance of {@link ExtractType }
     * 
     */
    public ExtractType createExtractType() {
        return new ExtractType();
    }

    /**
     * Create an instance of {@link TaskExtractRefreshType }
     * 
     */
    public TaskExtractRefreshType createTaskExtractRefreshType() {
        return new TaskExtractRefreshType();
    }

    /**
     * Create an instance of {@link FrequencyDetailsType.Intervals }
     * 
     */
    public FrequencyDetailsType.Intervals createFrequencyDetailsTypeIntervals() {
        return new FrequencyDetailsType.Intervals();
    }

    /**
     * Create an instance of {@link ViewType.Usage }
     * 
     */
    public ViewType.Usage createViewTypeUsage() {
        return new ViewType.Usage();
    }

    /**
     * Create an instance of {@link GranteeCapabilitiesType.Capabilities }
     * 
     */
    public GranteeCapabilitiesType.Capabilities createGranteeCapabilitiesTypeCapabilities() {
        return new GranteeCapabilitiesType.Capabilities();
    }

    /**
     * Create an instance of {@link SiteType.Usage }
     * 
     */
    public SiteType.Usage createSiteTypeUsage() {
        return new SiteType.Usage();
    }

}
