//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.22 at 09:54:58 AM CEST 
//


package org.knime.ext.tableau.hyper.sendtable.api.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serverSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serverSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oAuthEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sheetImageMaxAgeFloor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sheetImageMaxAgeCeiling" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="offlineInteractionSupportedPhase" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serverSettings", propOrder = {
    "oAuthEnabled",
    "sheetImageMaxAgeFloor",
    "sheetImageMaxAgeCeiling",
    "offlineInteractionSupportedPhase"
})
public class ServerSettings {

    protected boolean oAuthEnabled;
    protected int sheetImageMaxAgeFloor;
    protected int sheetImageMaxAgeCeiling;
    protected int offlineInteractionSupportedPhase;

    /**
     * Gets the value of the oAuthEnabled property.
     * 
     */
    public boolean isOAuthEnabled() {
        return oAuthEnabled;
    }

    /**
     * Sets the value of the oAuthEnabled property.
     * 
     */
    public void setOAuthEnabled(boolean value) {
        this.oAuthEnabled = value;
    }

    /**
     * Gets the value of the sheetImageMaxAgeFloor property.
     * 
     */
    public int getSheetImageMaxAgeFloor() {
        return sheetImageMaxAgeFloor;
    }

    /**
     * Sets the value of the sheetImageMaxAgeFloor property.
     * 
     */
    public void setSheetImageMaxAgeFloor(int value) {
        this.sheetImageMaxAgeFloor = value;
    }

    /**
     * Gets the value of the sheetImageMaxAgeCeiling property.
     * 
     */
    public int getSheetImageMaxAgeCeiling() {
        return sheetImageMaxAgeCeiling;
    }

    /**
     * Sets the value of the sheetImageMaxAgeCeiling property.
     * 
     */
    public void setSheetImageMaxAgeCeiling(int value) {
        this.sheetImageMaxAgeCeiling = value;
    }

    /**
     * Gets the value of the offlineInteractionSupportedPhase property.
     * 
     */
    public int getOfflineInteractionSupportedPhase() {
        return offlineInteractionSupportedPhase;
    }

    /**
     * Sets the value of the offlineInteractionSupportedPhase property.
     * 
     */
    public void setOfflineInteractionSupportedPhase(int value) {
        this.offlineInteractionSupportedPhase = value;
    }

}
